// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {request} from '../models';
import {response} from '../models';

export function CreateConnection(arg1:request.CreateConnection):Promise<response.CreateConnection>;

export function DeleteCredential(arg1:request.DeleteCredential):Promise<void>;

export function GetCredentials(arg1:request.GetCredentials):Promise<response.GetCredentials>;

export function GetTableColumns(arg1:request.GetTableColumns):Promise<Array<Record<string, any>>>;

export function GetTableRecords(arg1:request.GetTableRecords):Promise<response.GetTableRecords>;

export function GetTables(arg1:request.GetTables):Promise<Array<string>>;

export function SaveCredential(arg1:request.SaveCredential):Promise<void>;
