// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {request} from '../models';
import {response} from '../models';

export function CreateConnection(arg1:request.CreateConnection):Promise<void>;

export function GetTableColumns(arg1:string):Promise<Array<Record<string, any>>>;

export function GetTableRecords(arg1:request.GetTableRecords):Promise<response.GetTableRecords>;

export function GetTables():Promise<Array<string>>;
