// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['usecase']['Usecase']['CreateConnection'](arg1);
}

export function GetCredentials(arg1) {
  return window['go']['usecase']['Usecase']['GetCredentials'](arg1);
}

export function GetTableColumns(arg1) {
  return window['go']['usecase']['Usecase']['GetTableColumns'](arg1);
}

export function GetTableRecords(arg1) {
  return window['go']['usecase']['Usecase']['GetTableRecords'](arg1);
}

export function GetTables() {
  return window['go']['usecase']['Usecase']['GetTables']();
}

export function SaveCredential(arg1) {
  return window['go']['usecase']['Usecase']['SaveCredential'](arg1);
}
