// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {request} from '../models';

export function CreateConnection(arg1:request.CreateConnection):Promise<void>;

export function GetTables():Promise<Array<string>>;
